export const fakeData = {
  count: 10,
  next: "string",
  previous: "string",
  results: [
    {
      name: "Luke Skywalker",
      height: "172",
      mass: "77",
      hair_color: "blond",
      skin_color: "fair",
      eye_color: "blue",
      birth_year: "19BBY",
      gender: "male",
      homeworld: "Tatooine",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Human"],
      vehicles: ["X-34 landspeeder"],
      starships: ["X-wing", "Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Darth Vader",
      height: "202",
      mass: "136",
      hair_color: "none",
      skin_color: "white",
      eye_color: "yellow",
      birth_year: "41.9BBY",
      gender: "male",
      homeworld: "Tatooine",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Human"],
      vehicles: ["TIE Advanced x1", "Imperial Speeder Bike"],
      starships: ["Executor", "Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Princess Leia Organa",
      height: "150",
      mass: "49",
      hair_color: "brown",
      skin_color: "light",
      eye_color: "brown",
      birth_year: "19BBY",
      gender: "female",
      homeworld: "Alderaan",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Human"],
      vehicles: ["Tantive IV", "Imperial Speeder Bike"],
      starships: ["Millennium Falcon", "Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Han Solo",
      height: "180",
      mass: "80",
      hair_color: "brown",
      skin_color: "fair",
      eye_color: "brown",
      birth_year: "29BBY",
      gender: "male",
      homeworld: "Corellia",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Human"],
      vehicles: ["Millennium Falcon", "Imperial Speeder Bike"],
      starships: ["Millennium Falcon", "Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Chewbacca",
      height: "228",
      mass: "112",
      hair_color: "brown",
      skin_color: "unknown",
      eye_color: "blue",
      birth_year: "200BBY",
      gender: "male",
      homeworld: "Kashyyyk",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Wookiee"],
      vehicles: ["Millennium Falcon", "Imperial Speeder Bike"],
      starships: ["Millennium Falcon", "Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Obi-Wan Kenobi",
      height: "182",
      mass: "77",
      hair_color: "auburn",
      skin_color: "fair",
      eye_color: "blue-gray",
      birth_year: "57BBY",
      gender: "male",
      homeworld: "Stewjon",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Human"],
      vehicles: ["ETA-2 Actis-class interceptor", "Imperial Speeder Bike"],
      starships: [
        "Delta-7 Aethersprite-class interceptor",
        "Imperial Speeder Bike",
      ],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Yoda",
      height: "66",
      mass: "17",
      hair_color: "white",
      skin_color: "green",
      eye_color: "brown",
      birth_year: "896BBY",
      gender: "male",
      homeworld: "Unknown",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Yoda's species"],
      vehicles: ["Imperial Speeder Bike"],
      starships: ["Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "R2-D2",
      height: "96",
      mass: "32",
      hair_color: "n/a",
      skin_color: "white, blue",
      eye_color: "red",
      birth_year: "33BBY",
      gender: "n/a",
      homeworld: "Naboo",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Droid"],
      vehicles: ["Imperial Speeder Bike"],
      starships: ["Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "C-3PO",
      height: "167",
      mass: "75",
      hair_color: "n/a",
      skin_color: "gold",
      eye_color: "yellow",
      birth_year: "112BBY",
      gender: "n/a",
      homeworld: "Tatooine",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Droid"],
      vehicles: ["Imperial Speeder Bike"],
      starships: ["Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
    {
      name: "Anakin Skywalker",
      height: "188",
      mass: "84",
      hair_color: "blond",
      skin_color: "fair",
      eye_color: "blue",
      birth_year: "41.9BBY",
      gender: "male",
      homeworld: "Tatooine",
      films: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
      species: ["Human"],
      vehicles: ["Imperial Speeder Bike"],
      starships: ["Imperial Speeder Bike"],
      created: "dsadsa",
      edited: "dsadsa",
      url: "string",
    },
  ],
};
